string="My name is Nived Geethak"
print(string.casefold())
print(string.capitalize())
string.center(2)
print(string)
print(string.count("e"))
print(string.encode())
print(string.endswith("k"))
print(string.expandtabs(2))
print(string.find("v"))
print(string.index("d"))
print(string.isalnum())
print(string.isalpha())
print(string.isdecimal())
print(string.isdigit())
print(string.isidentifier())
print(string.islower())
print(string.isnumeric())
print(string.isprintable())
print(string.isspace())

myTuple=("You","Me","They")
print("-".join(myTuple))
txt = "banana"
x = txt.ljust(20)
print(x, "is my favorite fruit.")
print(string.lower())
print(string.partition("Nived"))
print(txt.split("n"))
string2="Welcome to programming\nEnjoy coding dude"
print(string2.splitlines())
print(string2.startswith("W"))
print(string2.strip())
print(string2.swapcase())
print(string2.title())
mydict={80: 83}
print(string2.translate(mydict))
print(string.upper())
print(txt.zfill(100))